# Human-owned: do not edit this file from the agent account.
{ ... }:
let
  entries = builtins.readDir ./.;
  names = builtins.filter
    (name: name != "default.nix" && entries.${name} == "regular"
      && builtins.match ".*\\.nix" name != null)
    (builtins.attrNames entries);
in
{
  imports = map (name: ./. + "/${name}") names;
}
