# Generated by an Aether agent. Risk level R1.
# Request: "install ripgrep and fd"
#
# One concern per file. Reverting this change means deleting this file and its
# line in default.nix.

{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    ripgrep
    fd
  ];
}
