# Generated by an Aether agent. Risk level R1.
# Request: "install ripgrep and fd"
#
# One concern per file. The protected loader imports it automatically.
# Reverting this change means removing this proposal through the reviewed flow.

{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    ripgrep
    fd
  ];
}
